# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-17 17:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='code',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='price_ht',
            field=models.DecimalField(decimal_places=2, default=datetime.datetime(2017, 4, 17, 17, 14, 44, 26126, tzinfo=utc), max_digits=8, verbose_name='Prix unitaire HT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_ttc',
            field=models.DecimalField(decimal_places=2, default=datetime.datetime(2017, 4, 17, 17, 14, 54, 755224, tzinfo=utc), max_digits=8, verbose_name='Prix unitaire TTC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Product', verbose_name='Produit'),
        ),
    ]
