# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-19 19:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20170417_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 19, 19, 14, 48, 709556, tzinfo=utc), verbose_name='Date création'),
        ),
    ]
