# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-19 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_auto_20170419_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 19, 19, 30, 50, 120462, tzinfo=utc), verbose_name='Date création'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, max_length=10, null=True, verbose_name='Prix unitaire HT'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, max_length=10, null=True, verbose_name='Prix unitaire TTC'),
        ),
    ]
