# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-19 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_auto_20170419_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 19, 19, 32, 6, 177286, tzinfo=utc), verbose_name='Date création'),
        ),
    ]
