# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-19 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_auto_20170419_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ht',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ttc',
        ),
    ]
